### ISSUE TITLE
Throw a mutex on my_hostport->jobs

### ISSUE THREAD

**Issue by colonelpanic8** [colonelpanic8/grid#25]
pretty important I would say.  This gets changed in dequeuing and enqueuing jobs.

**Comment by ghost** [comment]
are you talking about adding mutexs in my_hostport->jobs in rpc.c add_to_queue for this?

**Comment by colonelpanic8** [comment]
yes.  I did that.  Needs to be added also in get_local_job.  Also, in general, we need to use the mutex fields in the job_list_node when we are accessing elements of the job list
